### ISSUE TITLE
Deprecated version of IronRouterProgress

### ISSUE THREAD

**Issue by cubitworx** [LumaPictures/meteor-luma-ui#14]
Hi,

New to meteor & get the following console error when trying to use this package with Meteor 1.1.0.2:

```
Deprecated version of IronRouterProgress
Please run the following commands in your project:
    meteor remove mrt:iron-router-progress
    meteor add multiply:iron-router-progress
```

Looking at `versions.json` for this package it is clear that it uses `mrt:iron-router-progress`

Looking at the `mrt:iron-router-progress` package readme on atmosphere it states that as of Meteor V1 `multiply:iron-router-progress` should be used instead... https://atmospherejs.com/mrt/iron-router-progress

> Please note: From version 1.0 and onwards, you have to use multiply:iron-router-progress instead of mrt:iron-router-progress.
> The IronRouterProgress global has been removed. You now configure IRP using Router.configure, or on the route options object. See below, on how to do that.

Any ideas about when this package will be updated for Meteor > V1?

Thanks

**Comment by chadrik** [comment]
Hey @cubitworx, sorry to say that this project is not maintained anymore.   It's under the MIT license, so anyone can feel free to take it and do with it what they will.
